export const ROUTES = {
  root: '/',
  login: '/login',
  entries: '/entries',
  companies: '/companies',
  costCenters: '/cost-centers',
  budgets: '/budgets',
  allocations: '/allocations',
  assets: '/assets',
  accountsPayable: '/accounts-payable',
  suppliers: '/suppliers',
  bankReconciliation: '/bank-reconciliation',
  churchGeneralReport: '/reports/church-general',
  ministries: '/ministries',
  churchFinancial: '/church-financial',
  investments: '/investments',
  audit: '/audit',
  settings: '/settings',
} as const;
